### ISSUE TITLE
Git Workflow

### ISSUE THREAD

**Issue by AyudantesTecnicas** [mlafroce/template-tp-grupal#1]
Tienen que definir cual va a ser su workflow en Git. Pueden dejarlo especificado en una página de la Wiki.

https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow
http://nvie.com/posts/a-successful-git-branching-model/

**Comment by recheconea** [comment]
Nuestro workflow sera el siguiente:

- El branch "master" sera solo para releases
- Un branch develop sobre el que integrar los features
- Un branch por cada feature a desarrollar, brancheado de develop, sobre el cual se desarrolla y, una vez terminado, se integra a develop
