### ISSUE TITLE
Implementar nueva metadata - Parser

### ISSUE THREAD

**Issue by recheconea** [mlafroce/template-tp-grupal#35]
Implementar la nueva metadata:

GreaterThanCondition(String, int)
GreaterThanOtherCondition(String, String)
LowerThanCondition(String, int)
LowerThanOtherCondition(String, String)
SwapCondition(String, String)
IncrementalCondition(String, value)
DecrementalCondition(String, Value)

Aniadir la posibilidad de multiples conjuntos de condiciones para un action.

**Comment by demianLopez** [comment]
Voy a parsear todo como (String, String) y que después lo castie desde afuera, asi no tengo que parsear segun el tipo de metadata
