### ISSUE TITLE
Analisis pedido Entrega 2

### ISSUE THREAD

**Issue by agscontini** [mlafroce/template-tp-grupal#37]
Paso del tiempo como pide la consigna para ambos casos.

**Comment by agscontini** [comment]
- Para acciones random que dependan de un tiempo determinado, una alternativa sería incorporar en nuestro ActionManager (donde manejamos las executableActions, acciones que puede invocar el usuario, como las nonExecutableActions, accciones consecuentes de acciones de usuario), se podría incorporar un listado de acciones a ejecutar que dispongan de datos como, cada cuanto tiempo deben ser ejecutadas, (las acciones ya tienen las condiciones a cumplir del contexto del juego para ejecutarse). Además guardarían el tiempo en que ocurrió su última ejecución (se iniciarían con el mismo tiempo inicial de ejecución que el manejado por el juego en si (podría ser el timeMillis de java) y ya se calcularía el tiempo en segundos que falta para ser ejecutada. 
 En un thread aparte se pasaría el actionManager y aca se manejarían los tiempos (habría que manejar concurrencia para que no se pisen acciones del usuario con las temporales automáticas). El listado tendría las acciones dependientes del tiempo, el tiempo en timeMillis de su última ejecución y el tiempo en segundos que falta desde ese momento para ejecutarse. Se ordenaría el listado de menor a mayor por la que le falte menos tiempo para ejecutarse y se esperaría ese tiempo guardandolo en una variable de la clase; al despertar revisaría la primer acción del listado e intentaría ejecutar la acción correspondiente (esto implica corroborar que se cumplen las conditions del context, pero eso ya se hace por cada acción que se quiera ejecutar). Se recorrerían el resto de las acciones del listado, actualizando el tiempo para su ejecución usando la variable interna menos la usada para el sleep del thread. Se re ordena el listado y se mira en la primer acción del mismo para tomar el nuevo tiempo de sleep.
Estas acciones se levantarían en el archivo de configuración, habría que actualizar muy poco el parser para que contemple estas nuevas acciones, y el builder para que las construya. En el código se suma el thread con el comportamiento comentado y su clase, por que no, timeActionManager(o algo por el estilo) y el listado de estas acciones temporales. 
Hacer synchronized el método execute de actionManager para que no hayan inconsistencias entre las acciones del usuario y derivadas, con las temporales.

**Comment by demianLopez** [comment]
También se podría modelar el paso del tiempo como "cantidad de acciones ejecutadas", de ser así, suponiendo que cada acción ejecutada implica el paso de X unidades de tiempo, de ser ese el caso se puede realizar sin cambiar el modelo -> Basta crear tres states:
```json
{
        "name": "accionesTotales",
        "value": "0"
    }, {
        "name": "accionesParaMorir",
        "value": "0"
    }, {
        "name":"isPoison",
        "value":"0"
}
```
Tenes que crear 1 updateSet:
```json
{
        "executable": false,
        "label": "updateTotalActions",
        "update": [{
            "type": "++",
            "name": "object",
            "value": "1"
        }
```
y un actionSet:
```json
{
        "executable": false,
        "label": "CheckPoison",
        "cases": [{
            "do": [{
                "conditions": [{
                    "type": "greaterThanCondition",
                    "name": "accionesParaMorir",
                    "value": "accionesTotales"
                }, {
                    "type": "standarCondition",
                    "name": "isPoison",
                    "value": "1"
                }],
            }]}],
            "actions" : ["kill"]
```

Entonces cuando te envenenas tenes que setear el state "isPoison" a 1.
En "accionesParaMorir" = AccionesTotales + N (con N la cantidad de turnos hasta morir)
Esto ultimo se puede hacer armando un update que primero le asigne a "accionesParaMorir" el valor de "accionesTotales" y luego le sume N.

Finalmente para que esto funcione hay que llamar en TODAS LAS ACCIONES a "updateTotalActions" y "checkPoison".

Ventajas: No se debe modificar el programa:
Desventajas: Tenes que llamar a "updateTotalActions" y a "checkPoison" en todas las acciones armadas, lo cual incrementa la complejidad del archivo de configuración considerablemente.

Otra opción intermedia sería tener ya definida la variable global de tiempo internamente (tener un state que ya viene con el motor y es común a todos los juegos, que se pueda usar sin necesidad de ser definida) que lleve la cuenta del tiempo (acciones realizadas) y luego definir "actions" globales que se validen turno a turno (algo parecido a las winCondition), pero que a su vez estas puedan llamar a otras acciones (esto es para poder manejar todo tipo de eventos, no solo envenamiento).

CLARO ESTA, QUE TODO ES VALIDO SUPONIENDO QUE EL TIEMPO AVANZA ACCIÓN A ACCION, lo cual tiene sentido por ser un motor de aventuras gráficas
