### ISSUE TITLE
Corregir campos del json

### ISSUE THREAD

**Issue by recheconea** [mlafroce/template-tp-grupal#41]
Notamos que hay algunas incoherencias en algunos campos del json, por ejemplo, en algunos lugares se tiene el label conditions, y en otros se busca un condition. habria que validar que otros campos sufren del mismo problema y corregirlos

**Comment by demianLopez** [comment]
Es que el updateSet nunca tuvo conditions, esta al pedo, por mas que le pongas "condition" no lo parsea.
Lo agrego bajo el nombre "conditions" (igual como esta en el do de las actionSet), pasa que en el ejemplo configIdeal no hay ningún updateSet con condition y no lo tuve en cuenta
