### ISSUE TITLE
Agregar paso del tiempo - Estructura de acciones temporales

### ISSUE THREAD

**Issue by recheconea** [mlafroce/template-tp-grupal#44]
Para modelar las acciones que se ejecutan con el tiempo la idea principal es la creacion de una lista de acciones que contengan un tiempo de ejecucion y la accion a ejecutar. La idea principal es que cuando se triggerea una accion temporal, se agrega la misma a esta lista. con cada iteracion del reloj se consulta esta lista y, si se cumple el tiempo y alguna condicion extra, se ejecuta la misma. 
Esta lista deberia estar ordenada en funcion del tiempo, de esta forma solo consultariamos la primera de las acciones de la lista. Si estamos en el tiempo de ejecutar la misma, se la ejecuta y se realiza la segunda accion.
Si la accion ejecutada tiene que volver a ejecutarse, se calcular el proximo tiempo en el que deberia pasar eso y se la agrega nuevamente a la lista, en el tiempo correspondiente.

Hay, ademas, que crear updates nuevos que tenga la capcidad de agregar acciones temporales a estas listas.

**Comment by agscontini** [comment]
Se cambie un poco la mecanica, pero la idea basicamente es la misma. 
 Tiene para agregar tareas temporales que puedan surgir de otras acciones y mandarse a ejecutar en el momento el evento (la parte de cuando va a actuar va a surgir sola de los datos de en cuanto tiempo actua por primera vez la accion, que como toda accion puede encadenar varias acciones, y de cada cuanto tiempo se repite si esto es asi) pero me surgió la problemática de como devolver el mensaje para que se pueda mostrar. Por ahora se setea en una variable del actionManager a la que se le puede hacer un get, y una vez tirado por pantalla, tiene un metodo para volverlo a vacio.
 El tema es como ver que esa variable cambio porque la clase que uso extiende ya de algo y no le pude meter un observer, por eso pase al setter de este mensaje. Quizás se pueda tener en observación este campo mensaje y cuando se llama al set, se notifica y una vez leído, se tira el limpiar variable.
 Es para verlo, no me quedo muy lindo eso.

**Comment by recheconea** [comment]
Flavio estaba justamente por ver eso

**Comment by agscontini** [comment]
Tener en cuenta que el scheduler tiene los timeEvents a ejecutar con sus características, y este se puede llamar al principio pidiendo que se inicien todas las ejecuciones que manejan su propio tiempo de inicio (después de cuanto tiempo se inician por primera vez) y cada cuanto tiempo si asi lo hacen, se deben seguir llamando a las acciones de las mismas.

**Comment by agscontini** [comment]
También permite agregar un timeEvent en cualquier momento y al agregarlo que se ejecute automaticamente con la misma mecánica arriba explicada.
 Los timeEvents se pueden detener tmb: se detienen solos si tienen un 0 en el tiempo cada cuanto debe repetirse el evento, o llamando a frenarlo por un metodo.
 También hay uno para limpieza que los frena a todos los timeEvents del scheduler y limpia el hash de los mismos.

**Comment by agscontini** [comment]
Gente,
 Recién probé todo lo de las acciones temporales y tuve que corregir algo. Cuando la acción solo se ejecuta una vez, no puedo pasarle un 0 en el parametro de cada cuanto se repite, por lo que le puse el valor 99999999 como un periodo para ponerle a las acciones que solo se ejecutarían una sola vez. Esto después se multiplica por mil por eso la constante es 99999999000, y si ve que ese es el periodo en milisegundos para repetir la acción, luego de la primer ejecución la cancela.
 Hice las pruebas en un proyecto aparte y funciona bien. Cualquier duda me consultan.
