### ISSUE TITLE
Armar archivo de config para juego Abrir Puerta

### ISSUE THREAD

**Issue by recheconea** [mlafroce/template-tp-grupal#8]
> look around [Enter]
> There’s a key and a door in the room.
> open door. [Enter]
> Ey! Where do you go?! Room 2 is locked.
> pick key. [Enter]
> There you go!
> open door. [Enter]
> You enter room 2. You won the game!

**Comment by demianLopez** [comment]
Dejame que cuando termine el parser armo uno de ejemplo, al final para no perder tiempo con JSon use el XML que viene nativo con java. Igual lo arme de tal manera que se puede cambiar el reader por el de Json implementando un par de cositas mas. Asi que de ultima podemos tener los dos

**Comment by recheconea** [comment]
Joya, armate un ejemplo acá, así de ultima te damos una mano.
